// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ConfusionExtend","status":false,"description":"混乱ステート拡張プラグイン","parameters":{"味方対象スキルの対象":"false"}},
{"name":"ConfusionTargetEx","status":true,"description":"混乱等のステート時に自分をターゲットに含めない","parameters":{"SwitchId":"0","BehaviorOfRecoverAll":"0"}}
];
